Segformer Semantic Segmentation
WATonomous/wato_monorepo pull request #131
Opened 2024-06-14 02:01 UTC by lucasreljic

Node running:
https://github.com/WATonomous/wato_monorepo/assets/56940300/ba9daa71-dd97-4b28-b81b-c9282f3d53be
The model is: "segformer_mit-b2_8xb1-160k_cityscapes-1024x1024"

2024-06-14 02:25 UTC, danielrhuynh requested changes
Good stuff Lucas! Just a few catches from an overview before it gets to Eddy

2024-06-14 02:25 UTC, danielrhuynh commented on watod-config.sh
Remove this from PR

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +
Fix autopep

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +        #                                                    mode='bilinear',
Fix autopep here

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +COLOR_PALLETE = [
Fix autopep here

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/resource/deploy.yaml
> +Deploy:
Remove?

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/resource/cityscapes_demo.png
Remove photo?

2024-06-14 02:25 UTC, danielrhuynh commented on src/perception/semantic_segmentation/launch/semantic_segmentation.launch.py
> +
Fix autopep

2024-06-14 02:25 UTC, danielrhuynh commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +#  --from=Segformer /mmsegmentation/model /model
clean up comments

2024-06-14 02:25 UTC, danielrhuynh commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +#RUN pip install -r requirements.txt
Clean comment

2024-06-14 02:55 UTC, lucasreljic commented on src/perception/semantic_segmentation/resource/deploy.yaml
> +Deploy:
Done

2024-06-26 14:59 UTC, danielrhuynh approved these changes
Nice work!

2024-06-26 14:59 UTC, danielrhuynh commented
Wait for Eddie before merging tho

2024-07-01 19:05 UTC, Edwardius commented
Since this is a transformer, how much vram does this take up?

2024-07-01 19:17 UTC, Edwardius requested changes
Great work! A large portion of my concerns have to do with the size of the docker image, as well as the ros messages being used. 

To reduce the size of the docker image, there are two avenues:
1. wrap your head around docker caching to make MMLab stuff work
2. use a simpler repo that has an implementation of segformer, ie. https://github.com/lucidrains/segformer-pytorch

2024-07-01 19:17 UTC, Edwardius commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +        )
instead of outputting a segmented image, I would instead store the masks, in a custom message

2024-07-01 19:17 UTC, Edwardius commented on src/samples/python/aggregator/setup.py
>           glob(os.path.join('launch', '*.launch.py'))),
unintentional?

2024-07-01 19:17 UTC, Edwardius commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +package_share_directory = get_package_share_directory(package_name)
this should happen in the launch file, same place as where the yaml config is loaded

2024-07-01 19:17 UTC, Edwardius commented on src/perception/semantic_segmentation/semantic_segmentation/segmentation_node.py
> +]
all of these should be in the config

2024-07-19 00:08 UTC, danielrhuynh commented on src/samples/python/aggregator/setup.py
>           glob(os.path.join('launch', '*.launch.py'))),
The linter was complaining about this?

2024-07-19 02:03 UTC, lucasreljic commented
I moved all the config stuff in the yaml file, the docker file should be smaller now. The publisher message is still one Image but it's just the mask now. I can change to a boolean array (such as ByteMultiArray I think) or the new vision message you mentioned. Let me know which one I should implement.

2024-07-30 17:27 UTC, Edwardius approved these changes

2024-07-30 17:29 UTC, merged

2024-07-30 17:33 UTC, lucasreljic commented
Should a LabelInfo topic still be created for semantics, to map the class name to the int value in the mask?