Stgong/yolov8
WATonomous/wato_monorepo pull request #48
Opened 2024-01-25 22:17 UTC by Gongsta

Clean fork of justin's YOLOv8 PR https://github.com/WATonomous/wato_monorepo/pull/34/

2024-01-25 23:31 UTC, Gongsta commented
Tested and visualized on Foxglove 

<img width="1047" alt="Screenshot 2024-01-25 at 6 31 37 PM" src="https://github.com/WATonomous/wato_monorepo/assets/43485866/ea863312-edeb-4f0a-b555-fada9cbf3e56">

2024-01-27 21:03 UTC, Edwardius requested changes
Looks great, alot of the comments are about handling multiple cameras, which I feel should be handled sooner rather than later. We got a lot of ground to cover to build our AV as fast as we can, that's why I feel that we should make this program handle it.

resolve whenever u can

2024-01-27 21:03 UTC, Edwardius commented on src/wato_msgs/common_msgs/msg/BoundingBox.msg
also, any perception messages should go under `perception_msgs`

2024-01-28 18:57 UTC, Edwardius commented on src/perception/camera_detection/camera_detection/yolov8_detection.py
> +        self.publish_vis_topic = self.get_parameter('publish_vis_topic').value
OH! actually better yet you can map a publisher and subscriber to a specific camera topic

eg. self.publishers['/camera/left'] = <publisher>

2024-01-28 18:58 UTC, Edwardius commented on src/perception/camera_detection/camera_detection/yolov8_detection.py
> +        # TODO: Support reading stereo (left and right images)
Ignore this suggestion, should maybe consider: https://github.com/WATonomous/wato_monorepo/pull/48#discussion_r1468919888

2024-01-31 22:16 UTC, Gongsta commented on src/wato_msgs/common_msgs/CMakeLists.txt
> +set(msg_files
Agreed, removing all these in favor of standard vision_msgs

2024-01-31 22:30 UTC, Gongsta commented on docker/perception/camera_object_detection/camera_object_detection.Dockerfile
> +# Install pip
ack

2024-02-01 01:15 UTC, Gongsta commented on docker/perception/camera_object_detection/camera_object_detection.Dockerfile
> +RUN wget -P /perception_models https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt
done

2024-02-01 02:14 UTC, Gongsta commented on src/perception/camera_detection/camera_detection/yolov8_detection.py
> +                obstacle.header.frame_id = msg.header.frame_id
yup

2024-02-02 02:44 UTC, Gongsta commented on docker/perception/camera_object_detection/camera_object_detection.Dockerfile
> +RUN apt-fast update --fix-missing && apt-fast install -qq -y --no-install-recommends $(cat /tmp/colcon_install_list)
was due to storage, this was bad fix

2024-02-02 21:26 UTC, Edwardius requested changes
Please add test: Spawn node, send a single dummy image message, ensure that the node outputs bboxes

2024-02-02 21:26 UTC, Edwardius commented on docker/perception/camera_object_detection/camera_object_detection.Dockerfile
> +
move to line 26 so it doesn't have to reinstall stuff after a file change

2024-02-02 21:26 UTC, Edwardius commented on modules/docker-compose.perception.yaml
> +      - /mnt/wato-drive2/perception_models/:/perception_models
plz mount only the weight file, not the entire weights folder

2024-02-04 01:25 UTC, Edwardius approved these changes
LGTM: TODO for later, handle multi-camera with batch inference.

2024-02-04 02:32 UTC, merged