Add real time semantic segmentation node
WATonomous/wato_monorepo pull request #77
Opened 2024-02-18 09:58 UTC by leungjch

WIP

2024-03-14 16:10 UTC, Edwardius requested changes
Please break down the node into various files. 400 line monolith is not ideal :P

2024-03-14 16:10 UTC, Edwardius commented on src/perception/semantic_segmentation/src/semantic_segmentation_node.cpp
Split this into a header and a src file

2024-03-14 16:10 UTC, Edwardius commented on src/perception/semantic_segmentation/package.xml
> +  <test_depend>ament_lint_common</test_depend>
we arent using ament lint

2024-03-14 16:10 UTC, Edwardius commented on src/perception/semantic_segmentation/src/semantic_segmentation_node.cpp
> +    RCLCPP_INFO(this->get_logger(), "subscribing to image_topic: %s", image_topic.c_str());
move to where the subscriber is actually being init

2024-03-14 16:10 UTC, Edwardius commented on src/perception/semantic_segmentation/src/semantic_segmentation_node.cpp
> +  }
Place inside a separate utils file

2024-03-14 16:10 UTC, Edwardius commented on src/perception/semantic_segmentation/package.xml
> +  <depend>geometry_msgs</depend>
this doesnt seem to be used?

2024-03-14 16:11 UTC, Edwardius commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +ARG BASE_PROD_IMAGE=ghcr.io/watonomous/wato_monorepo/base:cuda12.0-humble-ubuntu22.04
RUNTIME_IMAGE

2024-03-14 16:12 UTC, Edwardius commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +ARG BASE_BUILD_IMAGE=ghcr.io/watonomous/wato_monorepo/base:cuda12.0-humble-ubuntu22.04-devel
BASE_IMAGE

2024-03-14 16:12 UTC, Edwardius commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +ARG BASE_PROD_IMAGE=ghcr.io/watonomous/wato_monorepo/base:cuda12.0-humble-ubuntu22.04
like lane detection

2024-03-14 16:27 UTC, Edwardius commented on src/perception/semantic_segmentation/src/semantic_segmentation_node.cpp
> +  }
and others

2024-03-14 17:03 UTC, Gongsta commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
> +ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${AMENT_WS}/install/semantic_segmentation/lib/paddle_inference_cuda120_build/paddle_inference_install_dir/third_party/install/mklml/lib/
yup, in the dev mode the path is slightly different

2024-03-14 17:04 UTC, Gongsta commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
>  ################################ Source ################################
Justin built the image from source to make it work with CUDA 12+

2024-03-14 17:04 UTC, Gongsta commented on docker/perception/semantic_segmentation/semantic_segmentation.Dockerfile
>  ################################ Source ################################
its published to our registry

2024-03-18 07:29 UTC, leungjch commented on src/perception/semantic_segmentation/src/semantic_segmentation_node.cpp
> +  }
put in a new package perception_utils

2024-03-18 07:31 UTC, leungjch commented on src/perception/semantic_segmentation/resource/dynamic_shape.pbtxt
think it's needed by the model config when loading it

2024-03-18 07:32 UTC, leungjch commented on src/perception/semantic_segmentation/CMakeLists.txt
> +set(PADDLE_LIB "/paddle/paddle_inference_cuda120_build/paddle_inference_install_dir") # Set this path as per your setup
my bad, this was copied from old cmakelists, removed now

2025-01-21 02:01 UTC, Edwardius approved these changes

2025-01-21 02:07 UTC, merged